[project]
name = "mcp-crash-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-mcp-adapters>=0.3.2",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
mcp-crash-course = "mcp_crash_course:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
